services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped 
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config #конфиги
      - /mnt/media:/media #медиафайлы
