services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config #конфиги
      - /mnt/media:/downloads #папка загрузок
